name: Generate Invoice

on:
  schedule:
    - cron: '0 0 1 * *'  # First day of every month
  workflow_dispatch:     # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install wkhtmltopdf  # required by pdfkit

    - name: Generate Invoice
      run: python scripts/generate_invoice.py

    - name: Commit Invoice
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add invoices/
        git commit -m "Add invoice for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
